# Generated by Django 3.1 on 2022-09-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenericApiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
