# Generated by Django 3.1 on 2022-09-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenericApiapp', '0002_auto_20220923_0530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
