# Generated by Django 3.2 on 2022-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiViewapp', '0003_auto_20220923_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
